# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\qwerty\Desktop\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 317)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 270, 81, 31))
        self.pushButton.setObjectName("pushButton")

        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(280, 70, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setChecked(True)

        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(280, 40, 91, 17))
        self.radioButton_2.setObjectName("radioButton_2")

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 251, 291))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 291))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet(
            """
            QWidget {background-color: #FFFFFF;}
            QScrollBar {background-color: none;}
            """
        )

        self.scrollAreaWidget = QtWidgets.QWidget()
        # self.scrollAreaWidget.setMinimumWidth(190)
        self.scrollAreaWidgetLayout = QtWidgets.QVBoxLayout()
        self.scrollAreaWidgetContents = []

        self.label_6 = QtWidgets.QLabel()
        self.label_6.setStyleSheet("color: #54595d;")
        self.label_6.setObjectName("label_6")
        self.label_6.mousePressEvent = lambda x: print(QtWidgets.QFileDialog.getExistingDirectory())
        self.scrollAreaWidgetContents.append(self.label_6)

        self.checkBox_12 = QtWidgets.QCheckBox()
        self.checkBox_12.setObjectName("checkBox_12")
        self.scrollAreaWidgetContents.append(self.checkBox_12)

        self.checkBox_10 = QtWidgets.QCheckBox()
        self.checkBox_10.setObjectName("checkBox_10")
        self.scrollAreaWidgetContents.append(self.checkBox_10)

        self.label_5 = QtWidgets.QLabel()
        self.label_5.setStyleSheet("color: #54595d;")
        self.label_5.setObjectName("label_5")
        self.scrollAreaWidgetContents.append(self.label_5)

        self.checkBox_11 = QtWidgets.QCheckBox()
        self.checkBox_11.setObjectName("checkBox_11")
        self.scrollAreaWidgetContents.append(self.checkBox_11)

        self.label_7 = QtWidgets.QLabel()
        self.label_7.setStyleSheet("color: #54595d;")
        self.label_7.setObjectName("label_7")
        self.scrollAreaWidgetContents.append(self.label_7)

        self.checkBox_13 = QtWidgets.QCheckBox()
        self.checkBox_13.setObjectName("checkBox_13")
        self.scrollAreaWidgetContents.append(self.checkBox_13)

        self.checkBox_14 = QtWidgets.QCheckBox()
        self.checkBox_14.setObjectName("checkBox_14")
        self.scrollAreaWidgetContents.append(self.checkBox_14)

        self.label_8 = QtWidgets.QLabel()
        self.label_8.setStyleSheet("color: #54595d;")
        self.label_8.setObjectName("label_8")
        self.scrollAreaWidgetContents.append(self.label_8)

        self.checkBox_15 = QtWidgets.QCheckBox()
        self.checkBox_15.setObjectName("checkBox_15")
        self.scrollAreaWidgetContents.append(self.checkBox_15)

        for content in self.scrollAreaWidgetContents:
            self.scrollAreaWidgetLayout.addWidget(content)

        for content in self.scrollAreaWidgetContents:
            self.scrollAreaWidgetLayout.addWidget(QtWidgets.QCheckBox('T Desktop'))

        self.scrollAreaWidgetLayout.addStretch()
        self.scrollAreaWidget.setLayout(self.scrollAreaWidgetLayout)
        self.scrollArea.setWidget(self.scrollAreaWidget)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 20, 111, 16))
        self.label.setStyleSheet("color: grey;\n"
"")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 396, 21))
        # self.menubar.setObjectName("menubar")
        # MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.radioButton.setText(_translate("MainWindow", "Delete"))
        self.radioButton_2.setText(_translate("MainWindow", "Move to folder"))
        self.label_6.setText(_translate("MainWindow", "Windows Applications"))
        self.checkBox_12.setText(_translate("MainWindow", "Telegram Desktop"))
        self.checkBox_10.setText(_translate("MainWindow", "Telegram Desktop1"))
        self.checkBox_11.setText(_translate("MainWindow", "Telegram Desktop"))
        self.label_5.setText(_translate("MainWindow", "Microsoft Applications"))
        self.checkBox_13.setText(_translate("MainWindow", "Telegram Desktop"))
        self.checkBox_14.setText(_translate("MainWindow", "Telegram Desktop1"))
        self.checkBox_15.setText(_translate("MainWindow", "Telegram Desktop"))
        self.label_7.setText(_translate("MainWindow", "Windows Applications"))
        self.label_8.setText(_translate("MainWindow", "Microsoft Applications"))
        self.label.setText(_translate("MainWindow", "C:\\Users\\Downloads"))
